### ISSUE TITLE
FrontEnd?

### ISSUE THREAD

**Issue by catHD** [4MAW/FFS#1]
Hello.

@Sumolari can you share frontend please?

**Comment by Sumolari** [comment]
We didn't develop a complete frontend but a very simple CLI and some bots to test the backend.

I've pushed it to [https://github.com/4MAW/FFS-NodeJS-Client](https://github.com/4MAW/FFS-NodeJS-Client). It's not documented and I really don't remember the details to set it up but feel free to play with it.

**Comment by catHD** [comment]
Big thx
